### ISSUE TITLE
About the state of the project

### ISSUE THREAD

**Issue by ironmaniiith** [pydsa/pydsa#109]
I am seeing many PR and issues not being resolved, is the project actively maintained by the collaborators.? This is really a very useful and awesome project, would love to contribute to this if it is actively maintained.

**Comment by CuriousLearner** [comment]
@ironmaniiith Yes we're trying hard to review PRs. But it takes time; since we've our day jobs. 

Rest assured, all PRs would be reviewed :)

**Comment by ironmaniiith** [comment]
:+1:
