### ISSUE TITLE
replacing range in python 2.7

### ISSUE THREAD

**Issue by ironmaniiith** [pydsa/pydsa#110]
I am seeing various range implementations like this.

``` python
for i in range(...):
  # code
```

However, range allocates memory first and then does the rest, which may lead to devastating conditions for large sized arrays in python 2.7. Better solution is to use `xrange` instead of `range` with for loops (which is also used by default in python 3.x)

**Comment by CuriousLearner** [comment]
Yes, xrange uses `yield`. It works just as a generator. Feel free to make a PR on this.

**Comment by ironmaniiith** [comment]
However, if this is implemented, it won't be supported in python 3.x. Can you update the docs for official python support (which pydsa does).?

**Comment by ironmaniiith** [comment]
But, if `xrange` is used, the code will break for python 3.x.
Also I don't see the module `future` for python compatibility (so that it can be handled easily using `builtins`)
I suggest to include `future` module in `install_requires` and then range can be used as such.
```python
from builtins import range
```
Any suggestions.?
