### ISSUE TITLE
Add script for removing whitespaces

### ISSUE THREAD

**Issue by aktech** [pydsa/pydsa#41]

**Comment by kanikaa1234** [comment]
From where should these white spaces be deleted?

**Comment by souravsingh** [comment]
Whitespace removal could be done by autopep8, I think. Or are you thinking of something like this-
http://paste.fedoraproject.org/355165/5778081/

**Comment by aktech** [comment]
> From where should these white spaces be deleted?

The extra whitespaces in any file.

**Comment by aktech** [comment]
You may take motivation from this: 
https://github.com/sympy/sympy/blob/master/bin/strip_whitespace

**Comment by kanikaa1234** [comment]
I want to take up this task, please assign it to me.

**Comment by CuriousLearner** [comment]
@souravsingh Don't use `new` as a variable name in your code.

@kanikaa1234 go ahead.

**Comment by souravsingh** [comment]
@CuriousLearner It was just a small sample code which I wrote

**Comment by CuriousLearner** [comment]
@souravsingh I meant whatever code you write, even if it's a sample code. It is not a good practice to use such variable names :)

**Comment by kanikaa1234** [comment]
We have made a PR ( #70 ) for this issue.

**Comment by kanikaa1234** [comment]
We have made the changes in PR ( #72 ).

**Comment by rahulroxx** [comment]
@aktech @CuriousLearner  I think that we should add pylint support in Travis CI , Let Pylint handle all the issues.

**Comment by kanikaa1234** [comment]
@rahulroxx, but ```Pylint``` will not remove the trailing spaces !!

**Comment by rahulroxx** [comment]
@kanikaa1234 Agreed ! It was meant for PR's ,flake8 is doing the same I closed the issue. Codebase is reformatted in #89 and #84
